name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  setup: 
    name: Setup Node.js and PNPM
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: npm install pnpm

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Install dependencies
        run: pnpm ci --frozen-lockfile
      - name: Run tests
        run: pnpm run test

  lint:
    name: Run lint check
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: pnpm run lint

  check-types:
    name: Check type definitions
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: pnpm run check-types